<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>MC7DTD.Bridge</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    
    <GameDir Condition="'$(GameDir)' == ''">D:\Steam\steamapps\common\7 Days To Die</GameDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src\*.cs" />
    <Compile Include="..\components\debug\DebugConfig.cs" Link="DebugConfig.cs" />
    <Compile Include="..\components\presentation\PresentationComponent.cs" Link="PresentationComponent.cs" />
    <Reference Include="Assembly-CSharp"><HintPath>$(GameDir)\7DaysToDie_Data\Managed\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="LogLibrary"><HintPath>$(GameDir)\7DaysToDie_Data\Managed\LogLibrary.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameDir)\7DaysToDie_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(GameDir)\7DaysToDie_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(GameDir)\7DaysToDie_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="UnityEngine.AnimationModule"><HintPath>$(GameDir)\7DaysToDie_Data\Managed\UnityEngine.AnimationModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AssetBundleModule"><HintPath>$(GameDir)\7DaysToDie_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(GameDir)\7DaysToDie_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(GameDir)\7DaysToDie_Data\Managed\Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <Target Name="PackageMod" AfterTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)\dist\MC7DTD-Bridge" />
    <Copy SourceFiles="$(TargetPath);$(MSBuildProjectDirectory)\ModInfo.xml" DestinationFolder="$(MSBuildProjectDirectory)\dist\MC7DTD-Bridge" />
  </Target>
</Project>

