using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEngine;
using UnityEngine.Animations;
using UnityEngine.Playables;
using Newtonsoft.Json;

namespace MC7DTD.AvatarExperiment {
 public struct PreviewAnimationJob : IAnimationJob {
  public TransformStreamHandle spine,leftArm,rightArm,leftLeg,rightLeg;
  public float time;public bool walk;
  public void ProcessRootMotion(AnimationStream stream){}
  public void ProcessAnimation(AnimationStream stream){float wave=Mathf.Sin(time*6.283185f);float swing=walk ? wave*25f:wave*1f;spine.SetLocalRotation(stream,Quaternion.Euler(0,0,wave));leftArm.SetLocalRotation(stream,Quaternion.Euler(-swing,0,90));rightArm.SetLocalRotation(stream,Quaternion.Euler(swing,0,-90));leftLeg.SetLocalRotation(stream,Quaternion.Euler(swing,0,0));rightLeg.SetLocalRotation(stream,Quaternion.Euler(-swing,0,0));}
 }
 [Serializable] public class ModelData {public float[] vertices;public float[] uv;public int[] triangles;public int[] weights;public BoneData[] bones;}
 [Serializable] public class BoneData {public string name;public string parent;public float[] position;}
 public sealed class AvatarPreview : IModApi {
  GameObject root;Mesh mesh;Material material;Texture2D texture;Avatar avatar;Animator animator;PlayableGraph graph;AnimationScriptPlayable procedural;string output,assetRoot;bool attempted,placed;int stage;float next,animationTime;
  readonly List<string> results=new List<string>();readonly Dictionary<string,Transform> bones=new Dictionary<string,Transform>();
  public void InitMod(Mod mod){assetRoot=Path.Combine(mod.Path,"Resources");output=Environment.GetEnvironmentVariable("AVATAR_PREVIEW_EVIDENCE") ?? Path.Combine(mod.Path,"Evidence");Directory.CreateDirectory(output);ModEvents.GameStartDone.RegisterHandler(OnStart);ModEvents.GameUpdate.RegisterHandler(OnUpdate);ModEvents.GameShutdown.RegisterHandler(OnStop);Log.Out("[AvatarPreview] isolated prototype loaded; no Entity/Equipment/Network/Authority integration");}
  void OnStart(ref ModEvents.SGameStartDoneData data){Start();}
  void Start(){if(attempted)return;attempted=true;try{Build();Test();}catch(Exception ex){Record("PROTOTYPE ERROR "+ex);Save();}}
  void OnUpdate(ref ModEvents.SGameUpdateData data){if(!attempted && GameManager.Instance?.World?.GetPrimaryPlayer()!=null)Start();if(graph.IsValid())Evaluate(Time.unscaledDeltaTime);var player=GameManager.Instance?.World?.GetPrimaryPlayer();if(root!=null && animator!=null && player!=null && !placed){root.transform.position=player.position+new Vector3(2,0,2)-Origin.position;placed=true;Record("WORLD_PREVIEW placed_near_local_player");Save();}if(animator!=null && Time.unscaledTime>next){next=Time.unscaledTime+4;stage++;try{PlayProcedure(stage%2!=0);}catch(Exception ex){Log.Warning("[AvatarPreview] preview animation: "+ex.Message);}}}
  void Build(){
   var data=JsonConvert.DeserializeObject<ModelData>(File.ReadAllText(Path.Combine(assetRoot,"alex_slim_mesh.json")));if(data?.bones==null || data.vertices==null || data.uv==null || data.weights==null || data.triangles==null)throw new InvalidDataException("Incomplete prototype mesh resource");root=new GameObject("IndependentAvatarPreviewProxy");root.layer=30;bones["Root"]=root.transform;
   foreach(var b in data.bones){var node=new GameObject(b.name);node.layer=30;node.transform.SetParent(bones[b.parent],false);node.transform.localPosition=new Vector3(b.position[0],b.position[1],b.position[2]);bones[b.name]=node.transform;}
   var transforms=data.bones.Select(b=>bones[b.name]).ToArray();var human=data.bones.Select(b=>new HumanBone{boneName=b.name,humanName=b.name,limit=new HumanLimit{useDefaultValues=true}}).ToArray();var skeleton=bones.Select(b=>new SkeletonBone{name=b.Key,position=b.Value.localPosition,rotation=b.Value.localRotation,scale=b.Value.localScale}).ToArray();
   avatar=AvatarBuilder.BuildHumanAvatar(root,new HumanDescription{human=human,skeleton=skeleton,upperArmTwist=.5f,lowerArmTwist=.5f,upperLegTwist=.5f,lowerLegTwist=.5f,armStretch=.05f,legStretch=.05f});
   mesh=new Mesh{name="AlexSlimTestMesh"};mesh.vertices=Enumerable.Range(0,data.vertices.Length/3).Select(i=>new Vector3(data.vertices[i*3],data.vertices[i*3+1],data.vertices[i*3+2])).ToArray();mesh.uv=Enumerable.Range(0,data.uv.Length/2).Select(i=>new Vector2(data.uv[i*2],data.uv[i*2+1])).ToArray();mesh.triangles=data.triangles;mesh.boneWeights=data.weights.Select(i=>new BoneWeight{boneIndex0=i,weight0=1}).ToArray();mesh.bindposes=transforms.Select(t=>t.worldToLocalMatrix*root.transform.localToWorldMatrix).ToArray();mesh.RecalculateNormals();mesh.RecalculateBounds();
   texture=new Texture2D(2,2,TextureFormat.RGBA32,false);bool loaded=ImageConversion.LoadImage(texture,File.ReadAllBytes(Path.Combine(assetRoot,"player_default.png")));texture.filterMode=FilterMode.Point;texture.wrapMode=TextureWrapMode.Clamp;
   var shader=Shader.Find("Unlit/Texture") ?? Shader.Find("Standard");if(shader==null)throw new Exception("texture shader missing");material=new Material(shader){mainTexture=texture};
   var visual=new GameObject("SkinnedVisual");visual.layer=30;visual.transform.SetParent(root.transform,false);var smr=visual.AddComponent<SkinnedMeshRenderer>();smr.sharedMesh=mesh;smr.bones=transforms;smr.rootBone=bones["Hips"];smr.sharedMaterial=material;smr.updateWhenOffscreen=true;
   animator=root.AddComponent<Animator>();animator.avatar=avatar;animator.applyRootMotion=false;animator.cullingMode=AnimatorCullingMode.AlwaysAnimate;root.transform.position=new Vector3(0,10000,0);
   Record("MODEL_LOAD "+(mesh.vertexCount==144 && smr.bones.Length>0 ? "PASS":"FAIL")+" vertices="+mesh.vertexCount+" skinned=true independent_root=true");Record("PNG_TEXTURE "+(loaded && texture.width==64 && texture.height==64 ? "PASS":"FAIL")+" size="+texture.width+"x"+texture.height);Record("HUMANOID_AVATAR "+(avatar.isValid && avatar.isHuman ? "PASS":"FAIL")+" isValid="+avatar.isValid+" isHuman="+avatar.isHuman);Capture("alex-slim-tpose.png");
  }
  AnimationClip[] GetClips(){var property=typeof(SDCSUtils).GetProperty("TPAnimController",BindingFlags.Public|BindingFlags.Static);var controller=property?.GetValue(null,null) as RuntimeAnimatorController;return controller?.animationClips ?? new AnimationClip[0];}
  static AnimationClip Find(AnimationClip[] clips,string term){return clips.Where(c=>c.isHumanMotion && c.name.IndexOf(term,StringComparison.OrdinalIgnoreCase)>=0).OrderBy(c=>c.name.Length).FirstOrDefault();}
  void Test(){var clips=GetClips();File.WriteAllLines(Path.Combine(output,"native-animation-clips.txt"),clips.Select(c=>c.name+":human="+c.isHumanMotion).Distinct());Record("NATIVE_HUMANOID_RETARGET "+(Find(clips,"Idle")!=null && Find(clips,"Walk")!=null ? "CANDIDATES_FOUND":"FAIL no_humanoid_idle_walk")+" total_clips="+clips.Length+" human_clips="+clips.Count(c=>c.isHumanMotion));foreach(var name in new[]{"Idle","Walk"}){PlayProcedure(name=="Walk");Evaluate(.1f);var before=bones.Values.Select(b=>b.localRotation).ToArray();var verticesBefore=BakedVertices();Evaluate(.25f);var verticesAfter=BakedVertices();float vertexDelta=verticesBefore.Select((v,i)=>Vector3.Distance(v,verticesAfter[i])).Average();float angle=bones.Values.Select((b,i)=>Quaternion.Angle(before[i],b.localRotation)).Sum();Record(name.ToUpperInvariant()+"_ANIMATOR "+(avatar.isValid && avatar.isHuman && angle>.01f && vertexDelta>.0001f ? "PASS":"FAIL")+" sampled_vertex_delta="+vertexDelta+" sampled_bone_delta="+angle+" animator=true animation_script_playable=true source=prototype_procedural");Capture("alex-slim-"+name.ToLowerInvariant()+".png");}Save();
   var player=GameManager.Instance?.World?.GetPrimaryPlayer();if(player!=null){root.transform.position=player.position+new Vector3(2,0,2)-Origin.position;placed=true;Record("WORLD_PREVIEW placed_near_local_player");Save();}
  }
  void Play(AnimationClip clip){if(graph.IsValid())graph.Destroy();graph=PlayableGraph.Create("AvatarPreviewAnimator");graph.SetTimeUpdateMode(DirectorUpdateMode.Manual);var output=AnimationPlayableOutput.Create(graph,"Preview",animator);var playable=AnimationClipPlayable.Create(graph,clip);playable.SetApplyFootIK(false);output.SetSourcePlayable(playable);graph.Play();}
  void PlayProcedure(bool walk){if(graph.IsValid())graph.Destroy();graph=PlayableGraph.Create("AvatarPreviewProceduralAnimator");graph.SetTimeUpdateMode(DirectorUpdateMode.Manual);var job=new PreviewAnimationJob{spine=animator.BindStreamTransform(bones["Spine"]),leftArm=animator.BindStreamTransform(bones["LeftUpperArm"]),rightArm=animator.BindStreamTransform(bones["RightUpperArm"]),leftLeg=animator.BindStreamTransform(bones["LeftUpperLeg"]),rightLeg=animator.BindStreamTransform(bones["RightUpperLeg"]),walk=walk};procedural=AnimationScriptPlayable.Create(graph,job);procedural.SetProcessInputs(false);var animationOutput=AnimationPlayableOutput.Create(graph,"Preview",animator);animationOutput.SetSourcePlayable(procedural);animationTime=0;graph.Play();}
  void Evaluate(float delta){animationTime+=delta;if(procedural.IsValid()){var job=procedural.GetJobData<PreviewAnimationJob>();job.time=animationTime;procedural.SetJobData(job);}graph.Evaluate(delta);}
  Vector3[] BakedVertices(){var baked=new Mesh();try{root.GetComponentInChildren<SkinnedMeshRenderer>().BakeMesh(baked);return baked.vertices;}finally{UnityEngine.Object.Destroy(baked);}}
  void Capture(string name){var smr=root.GetComponentInChildren<SkinnedMeshRenderer>();var baked=new Mesh();smr.BakeMesh(baked);baked.RecalculateBounds();var frozen=new GameObject("CurrentPoseCapture");frozen.layer=30;frozen.transform.SetParent(root.transform,false);frozen.AddComponent<MeshFilter>().sharedMesh=baked;frozen.AddComponent<MeshRenderer>().sharedMaterial=material;bool wasEnabled=smr.enabled;smr.enabled=false;var cameraObject=new GameObject("AvatarPreviewEvidenceCamera");var camera=cameraObject.AddComponent<Camera>();var render=new RenderTexture(512,512,24);Texture2D image=null;var old=RenderTexture.active;try{camera.targetTexture=render;camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.12f,.14f,.18f,1);camera.cullingMask=1<<30;camera.orthographic=true;camera.orthographicSize=Mathf.Max(1.15f,baked.bounds.size.y*.7f);var center=root.transform.TransformPoint(baked.bounds.center);camera.transform.position=center+new Vector3(2,.35f,3);camera.transform.LookAt(center);camera.Render();RenderTexture.active=render;image=new Texture2D(512,512,TextureFormat.RGB24,false);image.ReadPixels(new Rect(0,0,512,512),0,0);image.Apply();File.WriteAllBytes(Path.Combine(output,name),ImageConversion.EncodeToPNG(image));Record("CAPTURE "+name+" current_pose_baked=true height="+baked.bounds.size.y);}finally{RenderTexture.active=old;camera.targetTexture=null;smr.enabled=wasEnabled;frozen.SetActive(false);UnityEngine.Object.Destroy(frozen);UnityEngine.Object.Destroy(baked);UnityEngine.Object.Destroy(cameraObject);render.Release();UnityEngine.Object.Destroy(render);if(image!=null)UnityEngine.Object.Destroy(image);}}
  void Record(string message){results.Add(message);Log.Out("[AvatarPreview] "+message);}
  void Save(){File.WriteAllLines(Path.Combine(output,"prototype-results.txt"),results);}
  void OnStop(ref ModEvents.SGameShutdownData data){if(graph.IsValid())graph.Destroy();if(root!=null){root.SetActive(false);UnityEngine.Object.Destroy(root);}if(material!=null)UnityEngine.Object.Destroy(material);if(texture!=null)UnityEngine.Object.Destroy(texture);if(mesh!=null)UnityEngine.Object.Destroy(mesh);if(avatar!=null)UnityEngine.Object.Destroy(avatar);Record("CLEANUP scheduled");Save();}
 }
}
