<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><TargetFramework>net48</TargetFramework><LangVersion>latest</LangVersion><AssemblyName>MC7DTD.EquipmentExpansionSmoke</AssemblyName><GameManaged>D:\Steam\steamapps\common\7 Days To Die\7DaysToDie_Data\Managed</GameManaged></PropertyGroup>
 <ItemGroup>
  <Compile Include="../../7dtd-mod/src/AvatarEquipmentAnimation.cs" Link="AvatarEquipmentAnimation.cs" />
  <Compile Include="../../7dtd-mod/src/EquipmentRendererProvider.cs" Link="EquipmentRendererProvider.cs" />
  <Compile Include="../../7dtd-mod/src/EquipmentAttachment.cs" Link="EquipmentAttachment.cs" />
  <Compile Include="../../7dtd-mod/src/AvatarAnimatorDriver.cs" Link="AvatarAnimatorDriver.cs" />
  <Compile Include="../../7dtd-mod/src/AvatarActionState.cs" Link="AvatarActionState.cs" />
  <Compile Include="../../7dtd-mod/src/AvatarGroundAlignment.cs" Link="AvatarGroundAlignment.cs" />
  <Compile Include="../../7dtd-mod/src/AvatarMotionController.cs" Link="AvatarMotionController.cs" />
  <Compile Include="../../7dtd-mod/src/AvatarMotionSettings.cs" Link="AvatarMotionSettings.cs" />
  <Compile Include="../../7dtd-mod/src/AvatarRenderer.cs" Link="AvatarRenderer.cs" />
  <Compile Include="../../7dtd-mod/src/AvatarAnimationState.cs" Link="AvatarAnimationState.cs" />
  <Compile Include="../../7dtd-mod/src/AvatarProxyScene.cs" Link="AvatarProxyScene.cs" />
  <Compile Include="../../7dtd-mod/src/AvatarInspectorCommand.cs" Link="AvatarInspectorCommand.cs" />
  <Compile Include="../../7dtd-mod/src/LocalAvatarEquipmentAdapter.cs" Link="LocalAvatarEquipmentAdapter.cs" />
  <Compile Include="../../7dtd-mod/src/UnityPlayerProxyScene.cs" Link="UnityPlayerProxyScene.cs" />
  <Compile Include="../../7dtd-mod/src/MarkerController.cs" Link="MarkerController.cs" />
  <Compile Include="../../7dtd-mod/src/BridgeClient.cs" Link="BridgeClient.cs" />
  <Compile Include="../../7dtd-mod/src/IdentitySample.cs" Link="IdentitySample.cs" />
  <Compile Include="../../7dtd-mod/src/EntityDebugLog.cs" Link="EntityDebugLog.cs" />
  <Compile Include="../../components/debug/DebugConfig.cs" Link="DebugConfig.cs" />
  <Compile Include="../../components/presentation/PresentationComponent.cs" Link="PresentationComponent.cs" />
  <Reference Include="Assembly-CSharp"><HintPath>$(GameManaged)/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="LogLibrary"><HintPath>$(GameManaged)/LogLibrary.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameManaged)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="UnityEngine.AnimationModule"><HintPath>$(GameManaged)/UnityEngine.AnimationModule.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(GameManaged)/UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="UnityEngine.AssetBundleModule"><HintPath>$(GameManaged)/UnityEngine.AssetBundleModule.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(GameManaged)/UnityEngine.ImageConversionModule.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="Newtonsoft.Json"><HintPath>$(GameManaged)/Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="System.Runtime.Serialization" />
 </ItemGroup>
</Project>
